- include_role:
    name: docker
    tasks_from: network_create
  vars:
    docker_network: '{{ traefik_network }}'

- include_role:
    name: docker
    tasks_from: stack_deploy

# force reload
- include_role:
    name: docker
    tasks_from: service_update
  vars:
    options: --force
