- include_role:
    name: application
    tasks_from: make_config_dir
  vars:
    app_name: traefik

- include_role:
    name: application
    tasks_from: make_data_dir
  vars:
    app_name: traefik

- name: Ensure directories exists
  file: 
    path: '{{ directory }}'
    state: directory
  loop_control:
    loop_var: directory
  loop:
    - '{{ config_dir }}/dynamic'
    - '{{ config_dir }}/certs'
    - '{{ data_dir }}/acme'
  vars:
    app_name: traefik

- name: Render public certificates
  copy:
    content: '{{ item.crt }}'
    dest: '{{ config_dir }}/certs/{{ item.common_name }}.crt'
  with_items: '{{ traefik_certs }}'
  loop_control:
    label: "{{ item.common_name }}.crt"
  when: traefik_certs is defined
  vars:
    app_name: traefik

- name: Render private keys
  copy:
    content: '{{ item.key }}'
    dest: '{{ config_dir }}/certs/{{ item.common_name }}.key'
  with_items: '{{ traefik_certs }}'
  loop_control:
    label: "{{ item.common_name }}.key"
  when: traefik_certs is defined
  vars:
    app_name: traefik

- name: 'Render dynamic configuration for TLS Certs to {{ config_dir }}/dynamic/certs.yaml'
  template:
    src: certs.yaml
    dest: "{{ config_dir }}/dynamic/certs.yaml"
  vars:
    app_name: traefik

- name: 'Copy dynamic configuration from variable to {{ config_dir }}/dynamic/config.yaml'
  copy:
    content: '{{ traefik_config }}'
    dest: "{{ config_dir }}/dynamic/config.yaml"
  vars:
    app_name: traefik

- name: Allow port 80 (HTTP)
  ufw:
    rule: allow
    port: '80'
    proto: any
  become: yes

- name: Allow port 443 (HTTPS)
  ufw:
    rule: allow
    port: '443'
    proto: any
  become: yes

- name: Reload Firewall and enable at boot
  ufw:
    state: enabled
    policy: deny
  become: yes

- include_role:
    name: docker
    tasks_from: network_create
  vars:
    docker_network: '{{ traefik_network }}'
    options: --scope=swarm --driver=overlay

- include_role:
    name: docker
    tasks_from: stack_deploy
  vars:
    app_name: traefik

# force reload
- include_role:
    name: docker
    tasks_from: service_update
  vars:
    options: --force
    app_name: traefik
    docker_service: proxy

