- include_role:
    name: docker
    tasks_from: network_create
  vars:
    docker_network: '{{ traefik_network }}'

- include_role:
    name: docker
    tasks_from: stack_deploy
  vars:
    docker_compose_template: docker-compose.yaml

# TODO: Look into this more, Do we still need this? Enable hot reload?
# https://doc.traefik.io/traefik/providers/file/#provider-configuration
- name: Restart the service to pick up new dynamic configs
  shell: docker service update --force {{ repository }}_{{ version }}_proxy
  when: traefik_certs or traefik_dynamic_config
