- include_role:
    name: docker
    tasks_from: network_create
  vars:
    docker_network: '{{ traefik_network }}'

- include_role:
    name: docker
    tasks_from: stack_deploy

# force reload to pick up new config file changes
- when: traefik_certs 
  include_role:
    name: docker
    tasks_from: service_update
  vars:
    options: --force
